### ISSUE TITLE
Search is missing

### ISSUE THREAD

**Issue by iashraful** [edwin-abraham-thomas/LogLens#1]
Search is the primary requirement for reading logs. Without it it's incomplete.

**Comment by edwin-abraham-thomas** [comment]
Hi @iashraful,
Thank you for the suggestion.
The extension is in its alpha stage. Features are under development and will be available in the upcoming releases.

**Comment by edwin-abraham-thomas** [comment]
Hi @iashraful,
Basic free text search is available in the 0.1.8-alpha release.

**Comment by iashraful** [comment]
Thank you. I'll check it out.
